apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: sleep-retry
spec:
  destination:
    name: sleep
  route:
  - labels:
      version: v1
  httpReqRetries:
    simpleRetry:
      attempts: 3
      perTryTimeout: 2s
---
