apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: deploy-default
spec:
  destination:
    name: deploy
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10