apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deploy-ingress
  namespace: default
spec:
  rules:
  - host: deploy.jukylin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: deploy
          servicePort: 8080
